### ISSUE TITLE
Stability and future development of package

### ISSUE THREAD

**Issue by jonas-eschle** [N3PDF/vegasflow#50]
We're developing a general purpose model fitting library mainly based on TensorFlow, called [zfit](https://github.com/zfit/zfit), with a focus on High Energy Physics application. Since models can be multidimensional (up to 10 dims) and often lack an analytic integral, we've been looking for efficient MC integration packages. VEGAS is of course a well proven algorithm, so `vegasflow` seems like an interesting package. However, we were wondering about:

- what is the stability of the package? Do you expect many changes?
- would you be interested to "help contributing it" into zfit by guiding which parts are stable and provide some expert knowledge on when to best use it?
- What are the future plans for the package, will it be maintained? By whom and how long?
- is there any comparison with the [i-flow package](https://www.groundai.com/project/i-flow-high-dimensional-integration-and-sampling-with-normalizing-flows/1), which claims to be more efficient than the VEGAS algorithm?

**Comment by scarrazza** [comment]
@mayou36 thanks for your message and interest in `vegasflow`. 

Let me try to reply point by point:

> what is the stability of the package? Do you expect many changes?

In terms of development roadmap the package is stable and includes all features we believe are required for integration. We do not expect design changes but updates based on feature requests and/or new `tensorflow` releases for compatibility.

> would you be interested to "help contributing it" into zfit by guiding which parts are stable and provide some expert knowledge on when to best use it?
    
Yes, we are happy in contributing to zfit.

> What are the future plans for the package, will it be maintained? By whom and how long?

Yes, it will be maintained by @scarlehoff and myself.
  
> is there any comparison with the i-flow package, which claims to be more efficient than the VEGAS algorithm?

No, we do no compare to i-flow, because the focus of `vegasflow` is to implement the Vegas integration in a multi-GPU setup in order to get take full advantage of hardware acceleration performance.

Please let us know if you have further questions or requests.
