### ISSUE TITLE
Dependent integral limits

### ISSUE THREAD

**Issue by jackaraz** [N3PDF/vegasflow#88]
Hi I'm trying to take an integral where the second integral limit depends on the first integral, i.e.

$$ \int^a_b  \int^{f(x)}_{g(x)}  F(x,y) dx dy\quad , \quad g(x) < f(x)\ \forall x $$

I'm trying to modify ``VegasFlow`` where in ``_generate_random_array`` I use the ``rnds`` coming from ``_digest_random_generation`` to choose the first dimension and determine max min values for the second dimension according to these functions. Since my $\Delta x_{i>0}$ are now vectors, my Jacobian also becomes a vector, and I'm forming the new weights according to this Jacobian. But I believe I'm messing things up. Is there an easier way to take such an integral, or maybe I'm modifying the wrong function? Would be great if you guys could give me some tips to make this work.

Thanks!

**Comment by scarlehoff** [comment]
So you have an integral between (a, b), and for every point you want to compute a second integral, is that right?
But each of them is 1d? I'm not sure a Monte Carlo is the best approach. I would need to understand the problem a bit better, the way I see right now you are doing:

$$ \int^\vec{a}_\vec{b}   F(\vec{x}) d\vec{x} $$

And what the function $$F(\vec{x})$$ is not the business of the integration (and thus the random arrays and so have no reason to change).

Why is the jacobian a vector?

(there's clearly something I'm not understanding well...)

**Comment by scarlehoff** [comment]
Now I see, probably I shouldn't read github late at night :P 

 
One problem, regarding Vegas, is that I don't think you get any advantage from the Vegas adaptation by doing this (because it will be very confused as where the numbers should fall). So you might get the wrong number regardless just because the integral is numerically unstable.

Now to the specific technical problem:

You are at a point where you have a set of random numbers given by vegas and you have modified your set of `xmin` and `xdelta` to be what you want in every case:

- `rnds (n_events, n_dim)`
- `xdelta (n_dim,)` -> `xdelta (n_events, n_dim)`
- `wgts (n_events, n_dim)`

Since you are modifying the random numbers from going between 0 and 1 to `xmin` and `xmax` you need to do:

`wgts = wgts * tf.product(xdelta, axis=-1)` (so, get the product on the axis of `n_dim`)

This should give you the correct weight per point.


-----

That said, I would not do it this way. I would instead set the integration by vegas between 0 and 1 just the same for both `x` and `y` and make the transformation part of your integrand, for instance if you have:

$$
\int_0^1 dx \int_{x/2}^{2*x} dy cos(y)
$$

you could integrate it like:

```
from vegasflow import vegas_wrapper
import tensorflow as tf

def f(xarr, **kwargs):
    x = xarr[:, 0]
    rnd = xarr[:, 1]
    xdelta = 2.0*x - x/2.0
    y = x/2.0 + rnd*xdelta
    return tf.math.cos(y)*xdelta

result = vegas_wrapper(f, n_dim=2, n_iter=5, total_n_events=1000)
```

This way you don't need to modfiy the code. All transformations are done inside the integrand.

**Comment by jackaraz** [comment]
> Now I see, probably I shouldn't read github late at night :P

LoL! I feel you!

I tried it your way, but I still seem to be unable to match Mathematica results with Vegas. I tried the following:

$$
\int_{0.3}^\infty dy \int_{y/5}^{y^2} dx\ e^{-\frac{(x+y)^2 }{10}}
$$

So in mathematica, I can write it as follows:

```mathematica
NIntegrate[Exp[-(x+y)^2/10.],{y,0.3,\[Infinity]}, {x,xmin[y],xmax[y]}, MaxRecursion->12]
Out[54]= 1.79234
```

And it vegasflow it becomes

```python
def integrand(x, **kwrgs):
    y_rnd, x_rnd = tf.unstack(x, axis=1)
    y_r = 0.3 + y_rnd * 1e6 # to infty
    x_max = y_r**2
    x_min = y_r/5
    x_r = x_min + x_rnd * (x_max - x_min)
    return tf.exp(-(x_r+y_r)**2 / 10.)

vegas_wrapper(integrand, n_dim=2, n_iter=20, total_n_events=int(1e6))
# (1.2241970140295852e-06, 1.356844737073484e-10)
```

The difference seems to be too large, and the Vegas result keeps decreasing if I increase the upper limit on $y$. Even if I try easier limits on y, such as say, 0.3 to 1, I get the following:

```mathematica
NIntegrate[Exp[-(x+y)^2/10.],{y,0.3,1}, {x,xmin[y],xmax[y]}, MaxRecursion->12]
Out[69]= 0.20116
```

```python
def integrand(x, **kwrgs):
    y_rnd, x_rnd = tf.unstack(x, axis=1)
    y_r = 0.3 + y_rnd  # to one
    x_max = y_r**2
    x_min = y_r/5
    x_r = x_min + x_rnd * (x_max - x_min)
    return tf.exp(-(x_r+y_r)**2 / 10.)

vegas_wrapper(integrand, n_dim=2, n_iter=20, total_n_events=int(1e6))
# (0.8390801863274979, 9.691953333796514e-06)
```

Similarly, I can even leave $y\in[0,1]$, and Mathematica gives me 0.201147, whereas from Vegas, I get 0.931703. I'm not sure what I'm doing wrong (sorry for bugging you on this so much; thanks for your time; it's really appreciated!)

**Comment by scarlehoff** [comment]
What you are missing are the jacobian for both transformations as part of the integrand.
In the way you have it set (with the tf.unstack) is enough to get the deltas and multiply them at the end, for instance for the one from 0.3 to inf:
 
```python
def integrand(x, **kwrgs):
    y_rnd, x_rnd = tf.unstack(x, axis=1)
    y_r = 0.3 + y_rnd * 1e6 # to infty
    x_max = y_r**2
    x_min = y_r/5
    xdelta = (x_max - x_min)
    x_r = x_min + x_rnd * xdelta
    return tf.exp(-(x_r+y_r)**2 / 10.)*xdelta*1e6
```

instead for 0 to 1

```python
def integrand(x, **kwrgs):
    y_rnd, x_rnd = tf.unstack(x, axis=1)
    y_r = 0.3 + y_rnd*0.7 # to one
    x_max = y_r**2
    x_min = y_r/5
    x_r = x_min + x_rnd * (x_max - x_min)
    xdelta =  (x_max - x_min)
    return tf.exp(-(x_r+y_r)**2 / 10.)*xdelta*0.7
```

> sorry for bugging you on this so much; thanks for your time; it's really appreciated!

Not a problem at all. I'm happy to help ^__^

**Comment by jackaraz** [comment]
Aha, thanks for the clarification, awesome! 

Closing this issue, Thanks again was really helpful!

Side note: I love the package, by the way!
